### ISSUE TITLE
[ERROR] Invalid C2K server

### ISSUE THREAD

**Issue by eebssk1** [Magisk-Modules-Repo/optmizedgpsconf#5]
Why do u guys enable C2K PDE in this mod?It's useless as said in many guides
reference:https://rootzwiki.com/topic/28989-the-end-all-be-all-guide-to-your-gps/

**Comment by lazerl0rd** [comment]
@eebssk1 C2K itself isn't inavlid, it's just the domain we are currently using.I noticed from @Aefer that this domain is invalid, I'm just looking around for a decent one before I kill this off.

There is one issue with that guide tho, "1234" doesn't make a port bogus or fake at all. Anyone can put up any port to do what they like (even if not following the standards).

**Comment by eebssk1** [comment]
Closed due to inactivity (historitic issues cleanup).
