### ISSUE TITLE
Applying wrong conf on Dual cards devices (in China)

### ISSUE THREAD

**Issue by wl223600** [Magisk-Modules-Repo/optmizedgpsconf#6]
Dear developer:
It seems that the version updated a day ago didn't optmize for dual cards devices, which are very popular in China.
For example, on my OnePlus 3T(A3010, Oxygen OS 9.0, two Chinese operators' cards inserted), running 'getprop gsm.operator.iso-country' gets the output 'cn,cn' instead of 'cn'. So the install script applied the general conf instead of Chinese optimized one. When I put one card in slot 2 of dual card phones, 'getprop gsm.operator.iso-country' shows ",cn".
And if I change the "cn" to "cn,cn" in install.sh, files (optmized for China) extracted are in "/data/adb/modules/optmizedgpsconf/system_CN" folder (expected: /data/adb/modules/optmizedgpsconf/system"), which cannot take effect on /system.
Fogive my poor English and Bash knowledge.

**Comment by lazerl0rd** [comment]
Thanks, I'll fix that up for you.
